In [1]:
import numpy as np

In [2]:
np. array ([3,5,6,7,8])

array([3, 5, 6, 7, 8])

In [3]:
import numpy as np
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.linspace(15,5,25)

array([15.        , 14.58333333, 14.16666667, 13.75      , 13.33333333,
       12.91666667, 12.5       , 12.08333333, 11.66666667, 11.25      ,
       10.83333333, 10.41666667, 10.        ,  9.58333333,  9.16666667,
        8.75      ,  8.33333333,  7.91666667,  7.5       ,  7.08333333,
        6.66666667,  6.25      ,  5.83333333,  5.41666667,  5.        ])

In [6]:
import numpy as np 
np.arange (10,65,13)

array([10, 23, 36, 49, 62])

In [7]:
import numpy as np 
np.full((6,8),8)

array([[8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8]])

In [8]:
a=np.arange(24)
print(a.size )

24


In [2]:
import numpy as np
np.random.random((6,6))

array([[5.92167901e-01, 3.27229350e-01, 5.81998248e-01, 8.49337423e-01,
        9.43890269e-01, 9.70123247e-01],
       [6.31970824e-01, 1.57423954e-01, 9.46844051e-01, 4.42938894e-01,
        1.19020066e-01, 5.77813970e-01],
       [5.09008350e-01, 7.10936021e-01, 8.70875396e-01, 5.87727149e-01,
        8.25293952e-01, 9.57146455e-01],
       [3.95326418e-01, 7.97663016e-01, 6.88366341e-01, 2.25609758e-01,
        8.37785997e-01, 4.83361143e-01],
       [2.21006901e-04, 3.22704564e-01, 3.74567748e-01, 6.49557518e-01,
        1.99614263e-01, 4.69520776e-01],
       [9.94006946e-01, 8.52109899e-01, 7.94749486e-01, 4.19332234e-01,
        4.48744150e-01, 3.44852597e-01]])

In [4]:
import numpy as np
a=np.arange (24,dtype= float)
print(a.size)
print(a.dtype)

b= a.reshape(3,4,2)
b






24
float64


array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]])

In [5]:
import numpy as np 
np. sum([8,9])

17

In [6]:
a,b =10,20
np.sum([a,b])

30

In [7]:
import numpy as np
np.hstack(())

array([4, 7])